---
lowercaseOutputLabelNames: true
lowercaseOutputName: true
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1099/jmxrmi
# username: admin
# password: admin
blacklistObjectNames:
  - "org.apache.activemq:clientId=*,*"
whitelistObjectNames:
  - "org.apache.activemq:destinationType=Queue,*"
  - "org.apache.activemq:destinationType=Topic,*"
  - "org.apache.activemq:type=Broker,brokerName=*"
  - "org.apache.activemq:type=Topic,brokerName=*"
  - "java.lang:*"

rules:
  - pattern: java.lang<type=Memory><HeapMemoryUsage>max
    name: jvm_memory_heap_usage_max
  - pattern: java.lang<type=Memory><HeapMemoryUsage>used
    name: jvm_memory_heap_usage_used
  - pattern: java.lang<type=Memory><HeapMemoryUsage>committed
    name: jvm_memory_heap_usage_committed
  - pattern: java.lang<type=Memory><HeapMemoryUsage>init
    name: jvm_memory_heap_usage_init
  - pattern: java.lang<type=Memory><NonHeapMemoryUsage>max
    name: jvm_memory_nonheap_usage_max
  - pattern: java.lang<type=Memory><NonHeapMemoryUsage>used
    name: jvm_memory_nonheap_usage_used
  - pattern: java.lang<type=Memory><NonHeapMemoryUsage>committed
    name: jvm_memory_nonheap_usage_committed
  - pattern: java.lang<type=Memory><NonHeapMemoryUsage>init
    name: jvm_memory_nonheap_usage_init

  - pattern: org.apache.activemq<type=Broker, brokerName=(\S*), destinationType=Queue, destinationName=(\S*)><>(\w+)
    name: activemq_queue_$3
    attrNameSnakeCase: true
    labels:
      destination: $2

  - pattern: org.apache.activemq<type=Broker, brokerName=(\S*), destinationType=Topic, destinationName=(\S*)><>(\w+)
    name: activemq_topic_$3
    attrNameSnakeCase: true
    labels:
      destination: $2

  - pattern: org.apache.activemq<type=Broker, brokerName=(\S*)><>CurrentConnectionsCount
    name: activemq_connections
    type: GAUGE

  - pattern: org.apache.activemq<type=Broker, brokerName=(\S*)><>Total(.*)Count
    name: activemq_$2_total
    type: COUNTER

  - pattern: org.apache.activemq<type=Broker, brokerName=(\S*)><>(.*)PercentUsage
    name: activemq_$2_usage_ratio
    type: GAUGE
    valueFactor: 0.01
